language: java

#jdk:
#  - oraclejdk8


after_success:
  - mvn clean test
#  - mvn clean test jacoco:report
#  - mvn clean test jacoco:report coveralls:report


#notifications:
#  email:
#    - yoann.caplain@blackdread.org
